version: '3'
services:

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: admin
        PASS: admin
    restart: always
    networks: 
      - automation
    ports:
      - '9586:8080'
      - '8443:8443'
      - '8082:50000' 
    
    volumes:
      - data:/var/jenkins_home
      - '/var/run/docker.sock/var/run/docker.sock'
    
    #command: bash -c "chown -R jenkins:jenkins ./data"  
volumes: 
  data:
networks: 
  automation:
    driver: bridge

